# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
 production:
   AWS_ACCESS_KEY_ID: AKIAJTHO724B6KZPF6XQ
   AWS_SECRET_ACCESS_KEY: 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

   # mailgun私钥
   MAILGUN_PRI_KEY: key-06bf80eb430e74e4027cd3650a7fae30
   DOMAIN: 'http://law-firm.herokuapp.com'

 development:
   # mailgun私钥
   MAILGUN_PRI_KEY: key-06bf80eb430e74e4027cd3650a7fae30
   DOMAIN: 'http://localhost:3000'


