# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c000da070188e0c0a5db2cd2b3c57d3c81f1dc40e8e9b254b072b434000e65626f21791d732aaac010c800ebebcf88f83a6bc6375845ad7bf1feab112aeca7b9

test:
  secret_key_base: 44dda56d560c30b0415d8d17fa159cee29026770fab401b678811d92aa0b75d1b315c8a6bf218142d8b551d96a6a410fbeea228f9976fe708894cce7a3eb40b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
